---
- name: Install docker and docker compose
  package:
    name:
      - docker
      - docker-compose
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python
  when: ansible_pkg_mgr != 'homebrew'
- name: Create docker group
  group:
    name: docker
    state: present
  become: yes
- name: Add the user to the docker group
  ansible.builtin.user:
    name: "{{ lookup('env', 'USER') }}"
    shell: /bin/bash
    groups: docker
    append: yes
  become: yes
- name: Create the source directory {{ CHRIS_ULTRON_BACKEND_DIR }}
  file:
    name: "{{ CHRIS_ULTRON_BACKEND_DIR }}"
    state: directory
    owner: "{{ lookup('env', 'USER') }}"
  become: yes
- name: Check for the {{ CHRIS_ULTRON_BACKEND_README_PATH }}
  stat:
    path: "{{ CHRIS_ULTRON_BACKEND_README_PATH }}"
  register: CHRIS_ULTRON_BACKEND_README_PATH
- name: Clone the {{ CHRIS_ULTRON_BACKEND_NAME }} source code
  git:
    repo: "{{ CHRIS_ULTRON_BACKEND_REPO }}"
    dest: "{{ CHRIS_ULTRON_BACKEND_DIR }}"
  when: not CHRIS_ULTRON_BACKEND_README_PATH.stat.exists
- name: Start a docker swarm
  shell: docker swarm init --advertise-addr 127.0.0.1
  ignore_errors: true
  become: yes
