---
ISSUES_CHRIS_DIR: "/usr/local/src/issues-chris"
CHRIS_ULTRON_BACKEND_NAME: "ChRIS_ultron_backend"
CHRIS_ULTRON_BACKEND_DIR: "/usr/local/src/{{ CHRIS_ULTRON_BACKEND_NAME }}"
CHRIS_ULTRON_BACKEND_README_PATH: "{{ CHRIS_ULTRON_BACKEND_DIR }}/README.md"
CHRIS_ULTRON_BACKEND_REPO: "git@github.com:FNNDSC/{{ CHRIS_ULTRON_BACKEND_NAME }}.git"
